version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apologetyka_web
    environment:
      - VIRTUAL_HOST=apologetyka.placki.cloud
    networks:
      - nginx-proxy_net

networks:
  nginx-proxy_net:
    external: true
