version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local.ci
      args:
        BUNDLER_OPTIONS: "--jobs=5"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:9292"
